services:
  - type: web
    name: swami-medical-store
    env: node
    plan: free
    buildCommand: npm install && npm run build && npm run fetch-images
    startCommand: npm run server
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
